name: GithubActions 자동 배포

on:
  push:
    branches:
      - main

jobs:
  autodeploy:
    runs-on: ubuntu-latest

    steps:
      - name : test1
        run: echo "test"

      - name: test2
        run: |
          pwd
          ls -al