name: GithubActions 자동 배포

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name : github repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application yml 추가
        run: |
          mkdir -p src/main/resoureces || true
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resoureces/application.yml
          ls -al ./src/main/resoureces
          cat ./src/main/resources/applicaiton.yml
        

deploy-job:
  runs-on: ubuntu-latest